# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 866dfc36ed3522e82a167e6975d254893314c710cbf86710e270a8a5c2245e8f405112cf482e3970b600e0b89ccf8333081afcdd83e4b4cd2b218d11be88696d

test:
  secret_key_base: ff9ce606c5dbe48b0a7d0b76f4f0a24a3acb8a6c54b8312723cc0e299bd4cd42100e4554860e6949ab465ef8c1d1316f75a90a7432aa9240787b9bb7f49c4bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
